name: PyDev.Debugger Tests

on:
  push
  pull_request
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        name: [
          "windows-py27-master",
          "windows-py36-master",
          
          "ubuntu-py38-master",
          "ubuntu-pypy3-master",
          
          "ubuntu-py38-pip",
          "macos-py37",
        ]
        
        include:
          - name: "windows-py27-master"
            python: "2.7"
            os: windows-latest
          - name: "windows-py36-master"
            python: "3.6"
            os: windows-latest
          - name: "ubuntu-py38-master"
            python: "3.8"
            os: ubuntu-latest
          - name: "ubuntu-py38-pip"
            python: "3.8"
            os: ubuntu-latest
          - name: "ubuntu-pypy3-master"
            python: "pypy3"
            os: ubuntu-latest
          - name: "macos-py37"
            python: "3.7"
            os: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
